---
startDelaySeconds: 0
# hostPort: localhost:7779
#username:
#password:
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:8091/jmxrmi
ssl: false
#lowercaseOutputName: false
#lowercaseOutputLabelNames: false
# whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
# blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]
# metrics:name=app.lication.benjamin,type=counters
# metrics:name=app.lication.asdf,type=histograms
# metrics:name=app.lication.benny,type=meters
rules:
  - pattern: "app.lication.(.*), type=counters><>Count: (.*)"
    help: "$1 is $2"
    name: $1
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=histograms><>StdDev: (.*)"
    help: "standard deviation for $1 is $2"
    name: "$1_stddev"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=histograms><>Mean: (.*)"
    help: "mean for $1 is $2"
    name: "$1_mean"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=histograms><>Count: (.*)"
    help: "count for $1 is $2"
    name: "$1_count"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=histograms><>Max: (.*)"
    help: "max for $1 is $2"
    name: "$1_max"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=meters><>Count: (.*)"
    help: "count for $1 is $2"
    name: "$1_count"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=meters><>MeanRate: (.*)"
    help: "mean rate for $1 is $2"
    name: "$1_meanRate"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=meters><>OneMinuteRate: (.*)"
    help: "one minute rate for $1 is $2"
    name: "$1_oneMinRate"
    value: $2
    cache: false
  - pattern: "app.lication.(.*), type=meters><>FiveMinuteRate: (.*)"
    help: "give minute rate for $1 is $2"
    name: "$1_fiveMinRate"
    value: $2
    cache: false